### ISSUE TITLE
Bandomasis duomenų atvėrimas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/manifest#120]
Open Data Board planuoja atverti šiuos duomenų rinkinius:

- [ ] [Viešųjų prikimų duomens (VPT)](#15) 
- [ ] [Rinkimų duomenis (VRK)](#26)
- [ ] [Viešojo sektoriaus ir VVĮ/SVĮ buhalteriniai duomenys (FINMIN)](#12)
- [ ] [PVM mokėtojų duomenys (VMI)](#11)
- [ ] [Juridinių asmenų](#27) ir [adresų registrai](#28) (RC)
