### ISSUE TITLE
Supaprastinta duomenų rinkinio forma

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/manifest#55]
- [ ] Turi būti galimybė duomenų rinkinius redaguoti ne administravimo aplinkoje, o viešojoje dalyje, duomenų rinkinio peržiūros puslapyje, paspaudus mygtuką „Keisti“. Mygtukas „Keisti“ turi būti rodomas tik rinkinio administravimo teisę turintiems naudotojams.

Šiuo metu, duomenų rinkinio formoje yra 6 kortelės:

1. Inventorinimo duomenys
2. Struktūra
3. Prioritetai
4. Finansiniai duomenys
5. Metaduomenys
6. Duomenys

- [ ] Vietoj šių kortelių reikėtų palikti vieną formą, kurioje būtų galima keisti visus metaduomenis.

- [ ] Duomenų struktūros dalis turi būti [sujungta su distribucijų dalimi](#14). Duomenų struktūros failai turi būti įkeliame ne kaip failai, o importuojamas kaip distribucijų sąrašas.

- [ ] Duomenų dalis (arba distribucijų administravimas) turėtu būti iškeltas atskirai į [duomenų rinkinių peržiūros puslapyje esantį distribucijų sąrašą](#14).

- [ ] Prioritetų dalis naikinam ir keičiamai paklausos vertinimus, kuris [skaičiuojamas automatiškai](#9).

- [ ] Finansiniai duomenys perkeliami į atvėrimo finansavimų sąrašą.

- [ ] Metaduomenys perkeliame į pagrindinę duomenų rinkinio formą, paliekant tik tuos formos laukus, kuriuos galima redaguoti. Visi kiti laukai, kuriuose rodoma tik informacija, perkeliami į duomenų rinkinio peržiūros dalį.
